services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/cache:/cache
      - ${APP_DATA_DIR}/media:/media
